name: Test Automation for Projects

on:
  push:
    branches: [ main ]
    paths:
      - 'project/calculator_app/**'  # Trigger only for changes in path
  pull_request:
    branches: [ main ]
    paths:
      - 'project/calculator_app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project/calculator_app
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest tests/ --cov=calculator --cov-report=xml --cov-report=html --cov-fail-under=80

      - name: Upload coverage report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: project/htmlcov/
